apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate-webhook-pod
webhooks:
- name: validate-labels.k8s.io
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1EVXdPVEF6TVRrek1Wb1hEVEk1TURVd05qQXpNVGt6TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmdvCmtZQTRXOWlSMzVHR0piOFVBdlNpVkUzSlptNmduQmVWTmluclJoaHVjbUsreDN4ZHUwZU5xT2ZFQmNsRUh2OW0KZlVxMGRLN1FuSzliWWY2Vm1QZVFCeFNONVUyK2sycUhRNENVdVZnN0NhQUtmWktRZW96NEJFSlpzN3ZMYi9lcAp0cndOTGU2OVE0TW9CUFJKbVJQc2VUZjF2ZWNDVXRKbUNscDhDNXYrdmxya3llUmI3K1dBRTBBQ3dvNHd6eG1JCjNKeitLdkhwVGY1R2c4NngrVDliRDZSZHEzWGZYODhkblMyMUpYbFkxcWRCbnpqU1dtemNHTGtXODVnU2lxa2gKTDBhTkwrZ0lUWUM3L1YxVVliOUswaTNIMWhsbXh5ai9hM21uYUR1Y1N3OGJlZlc2dEtiSVk0azY4NzQwVWxFZworMkY4dXRkYUV0dit1SWw4c1hFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCWDI4WlZmeHJHa0lSd1c1YlNjZGY0Q0xhYzIKcmIyWXNWQmUyeXozMTlENGpVTkIxeE1qSzJnaEswT2NFWC9GYTB4T0dUR3k5REFVSmV2SFF4ZURyb3BaMEh3ZwpXa1djNFVRcEpmTFhOdjhkeDcvb2hmNm5ZdXAvekhoY0lSSDlFUThrZkhUV1JKYmh0QnF1RTJJOTIwbGc0RERyCmZUelZHY2JPYllKekY4VzZoamRXYk9yT2xBTWtzNExRY3hIZHVWRVlxYUVjR0luWFB1L2t0WDZ6TnltM0pRR2MKcWhpU1FDbzlSSGR4bWtVSnpDa3ZNR05GUnhiMG9CSWU3bkJ2UGF5RkF1NWtWTXdtRWxGNU9aWkQ0dU5oNEJRUQpNUHNyaE5lRkZOUXNwQzNwY3IxT05jOVNCdVFDbENRUElCK0NTdWN2Umw4VEx3d0toUWRWMXZaNHgwZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-svc
      namespace: webhook
      path: "/validate"
  namespaceSelector: {}
  rules:
  - apiGroups:
    - "apps"
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    - deployments
    - services
